# Generated by Django 4.1.7 on 2023-04-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_created_at_remove_todo_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
